# Form implementation generated from reading ui file 'ui\dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(270, 200)
        dlgSalir.setMinimumSize(QtCore.QSize(270, 20))
        dlgSalir.setMaximumSize(QtCore.QSize(270, 200))
        self.labelSalir = QtWidgets.QLabel(dlgSalir)
        self.labelSalir.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelSalir.setFont(font)
        self.labelSalir.setObjectName("labelSalir")
        self.labelImagen = QtWidgets.QLabel(dlgSalir)
        self.labelImagen.setGeometry(QtCore.QRect(100, 20, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelImagen.setFont(font)
        self.labelImagen.setText("")
        self.labelImagen.setPixmap(QtGui.QPixmap("ui\\../img/peligro.png"))
        self.labelImagen.setScaledContents(True)
        self.labelImagen.setObjectName("labelImagen")
        self.layoutWidget = QtWidgets.QWidget(dlgSalir)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 140, 158, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSalir = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSalir.setObjectName("buttonSalir")
        self.horizontalLayout.addWidget(self.buttonSalir)
        self.buttonCancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Dialog"))
        self.labelSalir.setText(_translate("dlgSalir", "¿Está seguro de que desea salir de la aplicación?"))
        self.buttonSalir.setText(_translate("dlgSalir", "Salir"))
        self.buttonCancelar.setText(_translate("dlgSalir", "Cancelar"))
