# Form implementation generated from reading ui file 'C:/Users/a21arielcg/PycharmProjects/costasguerrero/ui/dlgTipoImportacion.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogoTipoImportacion(object):
    def setupUi(self, dialogoTipoImportacion):
        dialogoTipoImportacion.setObjectName("dialogoTipoImportacion")
        dialogoTipoImportacion.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(dialogoTipoImportacion)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 250, 158, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonImportar = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonImportar.setObjectName("buttonImportar")
        self.horizontalLayout.addWidget(self.buttonImportar)
        self.buttonCancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)
        self.checkboxClientes = QtWidgets.QCheckBox(dialogoTipoImportacion)
        self.checkboxClientes.setGeometry(QtCore.QRect(40, 140, 76, 20))
        self.checkboxClientes.setObjectName("checkboxClientes")
        self.checkboxCoches = QtWidgets.QCheckBox(dialogoTipoImportacion)
        self.checkboxCoches.setGeometry(QtCore.QRect(40, 170, 76, 20))
        self.checkboxCoches.setObjectName("checkboxCoches")
        self.label = QtWidgets.QLabel(dialogoTipoImportacion)
        self.label.setGeometry(QtCore.QRect(50, 40, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(dialogoTipoImportacion)
        QtCore.QMetaObject.connectSlotsByName(dialogoTipoImportacion)

    def retranslateUi(self, dialogoTipoImportacion):
        _translate = QtCore.QCoreApplication.translate
        dialogoTipoImportacion.setWindowTitle(_translate("dialogoTipoImportacion", "Dialog"))
        self.buttonImportar.setText(_translate("dialogoTipoImportacion", "Importar"))
        self.buttonCancelar.setText(_translate("dialogoTipoImportacion", "Cancelar"))
        self.checkboxClientes.setText(_translate("dialogoTipoImportacion", "Clientes"))
        self.checkboxCoches.setText(_translate("dialogoTipoImportacion", "Coches"))
        self.label.setText(_translate("dialogoTipoImportacion", "¿Qué datos desea importar?"))
