# Form implementation generated from reading ui file 'C:/Users/a21arielcg/PycharmProjects/costasguerrero/ui/dlgTipoExportacion.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogoTipoExportacion(object):
    def setupUi(self, dialogoTipoExportacion):
        dialogoTipoExportacion.setObjectName("dialogoTipoExportacion")
        dialogoTipoExportacion.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(dialogoTipoExportacion)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 250, 158, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGuardar = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonGuardar.setObjectName("buttonGuardar")
        self.horizontalLayout.addWidget(self.buttonGuardar)
        self.buttonCancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.horizontalLayout.addWidget(self.buttonCancelar)
        self.checkboxClientes = QtWidgets.QCheckBox(dialogoTipoExportacion)
        self.checkboxClientes.setGeometry(QtCore.QRect(40, 140, 76, 20))
        self.checkboxClientes.setObjectName("checkboxClientes")
        self.checkboxCoches = QtWidgets.QCheckBox(dialogoTipoExportacion)
        self.checkboxCoches.setGeometry(QtCore.QRect(40, 170, 76, 20))
        self.checkboxCoches.setObjectName("checkboxCoches")
        self.label = QtWidgets.QLabel(dialogoTipoExportacion)
        self.label.setGeometry(QtCore.QRect(50, 40, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(dialogoTipoExportacion)
        QtCore.QMetaObject.connectSlotsByName(dialogoTipoExportacion)

    def retranslateUi(self, dialogoTipoExportacion):
        _translate = QtCore.QCoreApplication.translate
        dialogoTipoExportacion.setWindowTitle(_translate("dialogoTipoExportacion", "Dialog"))
        self.buttonGuardar.setText(_translate("dialogoTipoExportacion", "Guardar"))
        self.buttonCancelar.setText(_translate("dialogoTipoExportacion", "Cancelar"))
        self.checkboxClientes.setText(_translate("dialogoTipoExportacion", "Clientes"))
        self.checkboxCoches.setText(_translate("dialogoTipoExportacion", "Coches"))
        self.label.setText(_translate("dialogoTipoExportacion", "¿Qué datos desea exportar?"))
